workflow: update Github workflow summary
Signed-off-by: nullptr-t-oss <127822226+nullptr-t-oss@users.noreply.github.com>

diff --git a/.github/kernel/action.yml b/.github/kernel/action.yml
--- a/.github/kernel/action.yml
+++ b/.github/kernel/action.yml
@@ -341,7 +341,7 @@ runs:
         cd susfs4ksu
         if git rev-parse --verify "origin/$SUSFS_BRANCH" >/dev/null 2>&1 || git rev-parse --verify "$SUSFS_BRANCH" >/dev/null 2>&1; then
           git checkout "$SUSFS_BRANCH"
-          SUSFS_COMMIT_SHA=$(git rev-parse HEAD)
+          SUSFS_COMMIT_SHA=$(git rev-parse --short HEAD)
           echo "SUSFS_COMMIT_SHA=$SUSFS_COMMIT_SHA" >> $GITHUB_ENV
         else
           echo "Error: SUSFS branch or ref '$SUSFS_BRANCH' not found."
@@ -400,12 +400,12 @@ runs:
         fi
 
         cd ..
-        KSUN_COMMIT_SHA=$(git rev-parse HEAD)
-        echo "KSUN_COMMIT_SHA=$KSUN_COMMIT_SHA" >> $GITHUB_ENV
+        KSUN_COMMIT_SHA=$(git rev-parse --short HEAD)
+        echo "KSUN_COMMIT_SHA=${KSUN_COMMIT_SHA}" >> $GITHUB_ENV
 
         echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
         echo "KernelSU Next Version: $KSU_VERSION"
-        echo "KernelSU Next added (commit: ${KSUN_COMMIT_SHA:0:8}) ✅"
+        echo "KernelSU Next added (commit: ${KSUN_COMMIT_SHA}) ✅"
         echo "::endgroup::"
 
     - name: Apply SUSFS Patches
@@ -885,20 +885,6 @@ runs:
         echo "Build configs applied ✅"
         echo "::endgroup::"
 
-    - name: Save Build Metadata
-      id: save_metadata
-      shell: bash
-      run: |
-        set -euo pipefail
-        echo "::group::Saving Build Metadata..."
-        cd "$ARTIFACTS_DIR"
-        echo "kernel_version=${{ env.KERNEL_FULL_VER }}" >> "$GITHUB_OUTPUT"
-        echo "ksu_version=${KSUVER:-unknown}" >> "$GITHUB_OUTPUT"
-        echo "susfs_version=${SUSVER:-unknown}" >> "$GITHUB_OUTPUT"
-
-        echo "Build metadata saved ✅"
-        echo "::endgroup::"
-
     - name: Customize Kernel Branding
       shell: bash
       run: |
@@ -982,6 +968,7 @@ runs:
         INSTALL_MOD_PATH="$COMMON/out"
         mkdir -p "$OUT"
         make "${MAKE_FLAGS[@]}" O="$OUT" gki_defconfig
+        echo "kernel_release=$(make "${MAKE_FLAGS[@]}" O="$OUT" -s kernelrelease)" >> "$GITHUB_ENV"
 
         if [ "${{ inputs.optimize_level }}" = "O3" ]; then
           KCFLAGS_EXTRA="-O3"
@@ -1002,9 +989,13 @@ runs:
         KCPPFLAGS="-DCONFIG_OPTIMIZE_INLINING"
 
         echo "Starting build with $(nproc --all) threads..."
+        SECONDS=0
+
         make "${MAKE_FLAGS[@]}" O="$OUT" olddefconfig
         make -j$(nproc --all) "${MAKE_FLAGS[@]}" KCFLAGS="$KCFLAGS" KCPPFLAGS="$KCPPFLAGS" O="$OUT" Image modules
         make -j$(nproc --all) "${MAKE_FLAGS[@]}" O="$OUT" INSTALL_MOD_STRIP=1 INSTALL_MOD_PATH="$INSTALL_MOD_PATH" modules_install
+
+        echo "duration=$SECONDS" >> "$GITHUB_ENV"
 
         IMG="$OUT/arch/arm64/boot/Image"
         if [ ! -f "$IMG" ]; then
@@ -1110,6 +1101,7 @@ runs:
 
     - name: Create Boot Image
       if: success() && steps.create_zip.conclusion == 'success'
+      id: create_boot
       shell: bash
       run: |
         set -euo pipefail
@@ -1142,6 +1134,8 @@ runs:
           --key "$KERNEL_PLATFORM/tools/mkbootimg/gki/testdata/testkey_rsa4096.pem"
 
         cp "$OUT/boot.img" "$ARTIFACTS_DIR"
+        BOOT_SHA256=$(sha256sum "$OUT/boot.img" | cut -d' ' -f1)
+        echo "boot_sha256=${BOOT_SHA256:-ERROR}" >> "$GITHUB_OUTPUT"
 
         echo "Boot image created ✅"
         echo "::endgroup::"
@@ -1192,47 +1186,57 @@ runs:
             --partition_name system_dlkm \
             --image "$OUT/system_dlkm.img"
 
+        SYSTEM_DLKM_SHA256=$(sha256sum "$OUT/system_dlkm.img" | cut -d' ' -f1)
+        echo "system_dlkm_sha256=${SYSTEM_DLKM_SHA256:-ERROR}" >> "$GITHUB_OUTPUT"
+
         cp "$OUT/system_dlkm.img" "$ARTIFACTS_DIR"
         cp "$OUT/system_dlkm.modules.load" "$ARTIFACTS_DIR"
         cp "$OUT/system_dlkm.modules.load" "$ARTIFACTS_DIR_DEBUG"
+
+    - name: Format build time
+      id: build_time
+      shell: bash
+      run: |
+        set -euo pipefail
+
+        if [ "$duration" -ge 60 ]; then
+          duration="$((duration / 60))m $((duration % 60))s"
+        else
+          duration="${duration}s"
+        fi
+
+        echo "duration=$duration" >> "$GITHUB_OUTPUT"
 
     - name: Final Build Summary
       shell: bash
       run: |
         set -euo pipefail
         {
-          echo "Model: ${MODEL}"
-          echo "Android: ${{ env.ANDROID_RELEASE }}"
-          echo "Kernel base: ${{ env.KERNEL_VER }}"
-          echo "Kernel full: ${{ env.KERNEL_FULL_VER }}"
-          echo "Kernel Uname: ${{ env.KERNEL_UNAME }}"
-          echo "KSUN Version: ${KSUVER:-unknown}"
-          echo "KSUN commit SHA: ${{ env.KSUN_COMMIT_SHA }}"
-          echo "SUSFS Version: ${SUSVER:-unknown}"
-          echo "SUSFS commit SHA: ${{ env.SUSFS_COMMIT_SHA }}"
-          echo "Optimization: ${{ inputs.optimize_level }}"
-          echo "Image SHA256: ${{ steps.collect_stats.outputs.image_sha256 }}"
-          echo "Compiler: ${CLANG_VERSION:-unknown}"
-          echo ""
-          echo "CCache Statistics :"
-          echo "$(ccache -s -v)"
-        } | tee summary.txt
-        {
           echo "### Kernel Build Summary"
+          echo "----"
           echo ""
-          echo "- Model: ${{ env.MODEL }}"
-          echo "- Android: ${{ env.ANDROID_RELEASE }}"
-          echo "- Kernel Version: ${{ steps.save_metadata.outputs.kernel_version }}"
+          echo "> [!NOTE]"
+          echo "> Model: ${{ env.MODEL }}"
+          echo ""
+          echo "- Kernel Release: ${{ env.kernel_release }}"
           echo "- Kernel Uname: ${{ env.KERNEL_UNAME }}"
           echo "- KSUN Version: ${KSUVER:-unknown}"
           echo "- KSUN commit SHA: [${{ env.KSUN_COMMIT_SHA }}](https://github.com/KernelSU-Next/KernelSU-Next/commit/${{ env.KSUN_COMMIT_SHA }})"
           echo "- SUSFS Version: ${SUSVER:-unknown}"
           echo "- SUSFS commit SHA: [${{ env.SUSFS_COMMIT_SHA }}](https://gitlab.com/simonpunk/susfs4ksu/-/commit/${{ env.SUSFS_COMMIT_SHA }})"
           echo "- Optimization: ${{ inputs.optimize_level }}"
-          echo "- Image SHA256: ${{ steps.collect_stats.outputs.image_sha256 }}"
           echo ""
-          echo "CCache Statistics :"
-          echo "$(/usr/bin/ccache -s)"
+          echo "> [!IMPORTANT]"
+          echo "> - Kernel Image SHA256: ${{ steps.collect_stats.outputs.image_sha256 }}"
+          echo "> - Boot image SHA256: ${{ steps.create_boot.outputs.boot_sha256 }}"
+          echo "> - System dlkm image SHA256: ${{ steps.create_system_dlkm.outputs.system_dlkm_sha256 }}"
+          echo ""
+          echo "> [!NOTE]"
+          echo "> Build completed in ${{ steps.build_time.outputs.duration }}"
+          echo ""
+          echo "> [!IMPORTANT]"
+          echo "> ## CCache Statistics :"
+          echo "> $(ccache -s -v)"
         } >> "$GITHUB_STEP_SUMMARY"
 
     - name: Cleanup old ccache
diff --git a/.github/kernel_modules/action.yml b/.github/kernel_modules/action.yml
--- a/.github/kernel_modules/action.yml
+++ b/.github/kernel_modules/action.yml
@@ -26,7 +26,7 @@ inputs:
     type: string
     default: ""
   prebuilt_dtb:
-    description: 'Do you want to use prebuilt dtb for vndr boot?'
+    description: 'Do you want to use prebuilt dtb for vendor boot?'
     required: false
     type: string
     default: 'true'
@@ -462,11 +462,15 @@ runs:
             --enable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE \
             --disable CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE_O3
 
+        SECONDS=0
+
         echo "Building kernel modules and dtbs..."
         make "${MAKE_FLAGS[@]}" O=$OUT olddefconfig
         make -j$(nproc --all) "${MAKE_FLAGS[@]}" O="$OUT" modules dtbs
         make -j$(nproc --all) "${MAKE_FLAGS[@]}" O="$OUT" INSTALL_MOD_STRIP=1 INSTALL_MOD_PATH="$INSTALL_MOD_PATH" modules_install
         make -j$(nproc --all) "${MAKE_FLAGS[@]}" O="$OUT" INSTALL_DTBS_PATH="$INSTALL_DTBS_PATH" DTB_TYPES="$DTB_TYPES" dtbs_install
+
+        echo "duration=$SECONDS" >> "$GITHUB_ENV"
 
         cd "$KERNEL_PLATFORM"
 
@@ -490,12 +494,15 @@ runs:
         )
 
         echo "Compiling vendor modules (oplus)"
+        SECONDS=0
 
         # OPLUS ext modules
         for MODULE in "${EXT_OPLUS[@]}"; do
             make -C "$MODULE" M="../$MODULE" -j$(nproc --all) "${MAKE_FLAGS[@]}" O=$MSM/out "${OPLUS_FLAGS[@]}"
             make -C "$MODULE" M="../$MODULE" -j$(nproc --all) "${MAKE_FLAGS[@]}" O=$MSM/out "${OPLUS_FLAGS[@]}" INSTALL_MOD_STRIP=1 INSTALL_MOD_PATH=$INSTALL_MOD_PATH modules_install
         done
+
+        echo "duration_oplus_ext=$SECONDS" >> "$GITHUB_ENV"
 
         # QCOM ext modules
         EXT_QCOM+=(
@@ -531,6 +538,7 @@ runs:
         export KBUILD_EXTRA_SYMBOLS=""
 
         echo "Compiling vendor modules (qcom)"
+        SECONDS=0
 
         for MODULE in "${EXT_QCOM[@]}"; do
             make -C "$MODULE" M="../$MODULE" -j$(nproc --all) "${MAKE_FLAGS[@]}" O=$MSM/out "${OPLUS_FLAGS[@]}"
@@ -538,7 +546,10 @@ runs:
             export KBUILD_EXTRA_SYMBOLS=$(find "$KERNEL_PLATFORM/vendor" -name "Module.symvers" | tr '\n' ' ')
         done
 
+        echo "duration_qcom_ext=$SECONDS" >> "$GITHUB_ENV"
+
         echo "Compiling vendor devicetree overlays"
+        SECONDS=0
 
         for PROJECT in $(cd "$CONFIG_DIR" && find -L vendor/ -maxdepth 4 -type d -name "*-devicetree"); do
           if [ ! -e "../$PROJECT/Makefile" ]; then
@@ -547,6 +558,8 @@ runs:
           fi
           make -C "../$PROJECT" M="../../$PROJECT" -j$(nproc --all) "${MAKE_FLAGS[@]}" O=$MSM/out "${OPLUS_FLAGS[@]}"
         done
+
+        echo "duration_dtb_ext=$SECONDS" >> "$GITHUB_ENV"
 
         # To be used for preparing modules.order in create_vendor_dlkm step
         EXT_MODULES=("${EXT_OPLUS[@]#../}" "${EXT_QCOM[@]#../}") >> "$GITHUB_ENV"
@@ -581,12 +594,12 @@ runs:
         OUT="$MSM/out"
         UNAME=$(ls "$OUT/lib/modules/")
         MODULES_STAGING_ROOT="$OUT/lib/modules/$UNAME"
-        VNDR_BOOT_STAGING_DIR="$OUT/vendor_boot_staging"
-        RAMDISK_STAGING_DIR="$VNDR_BOOT_STAGING_DIR/ramdisk"
+        VENDOR_BOOT_STAGING_DIR="$OUT/vendor_boot_staging"
+        RAMDISK_STAGING_DIR="$VENDOR_BOOT_STAGING_DIR/ramdisk"
         RAMDISK_STAGING_MODULES="$RAMDISK_STAGING_DIR/lib/modules"
         DEPMOD_DIR="$RAMDISK_STAGING_DIR"
         # After depmod delete this dir since ramdisk is flattened
-        DEPMOD_DIR_ROOT="$VNDR_BOOT_STAGING_DIR/ramdisk/lib/modules/$UNAME"
+        DEPMOD_DIR_ROOT="$VENDOR_BOOT_STAGING_DIR/ramdisk/lib/modules/$UNAME"
 
         export PATH="$KERNEL_PLATFORM/build/build-tools/path/linux-x86:$PATH"
 
@@ -633,7 +646,7 @@ runs:
         cd "$RAMDISK_STAGING_DIR/first_stage_ramdisk"
         curl -sL -o fstab.qcom "$PREBUILTS/vendor_boot/vendor_ramdisk/first_stage_ramdisk/fstab.qcom"
 
-        cd "$VNDR_BOOT_STAGING_DIR"
+        cd "$VENDOR_BOOT_STAGING_DIR"
 
          # Create cpio compressed ramdisk using mkbootfs; use cpio like cyberknight777 did in his YAKB??
         mkbootfs "$RAMDISK_STAGING_DIR" > "$OUT/ramdisk.cpio"
@@ -665,6 +678,9 @@ runs:
           --image "$OUT/vendor_boot.img" \
           --algorithm "SHA256_RSA4096" \
           --key "$KERNEL_PLATFORM/tools/mkbootimg/gki/testdata/testkey_rsa4096.pem"
+
+        VENDOR_BOOT_SHA256=$(sha256sum "$OUT/vendor_boot.img" | cut -d' ' -f1)
+        echo "vendor_boot_sha256=${VENDOR_BOOT_SHA256:-ERROR}" >> "$GITHUB_OUTPUT"
 
         cp "$RAMDISK_STAGING_MODULES/modules.load" "$OUT/vendor_boot.modules.load"
         cp "$RAMDISK_STAGING_MODULES/modules.load.recovery" "$OUT/vendor_boot.modules.load.recovery"
@@ -760,6 +776,9 @@ runs:
 
         build_image "$DLKM_STAGING_DIR" "${vendor_dlkm_props_file}" "$OUT/vendor_dlkm.img" /dev/null
 
+        VENDOR_DLKM_SHA256=$(sha256sum "$OUT/vendor_dlkm.img" | cut -d' ' -f1)
+        echo "vendor_dlkm_sha256=${VENDOR_DLKM_SHA256:-ERROR}" >> "$GITHUB_OUTPUT"
+
         cp "$OUT/vendor_dlkm.img" "$ARTIFACTS_DIR"
         cp "$OUT/vendor_dlkm.modules.load" "$ARTIFACTS_DIR"
         cp "$OUT/vendor_dlkm.modules.load" "$ARTIFACTS_DIR_DEBUG"
@@ -805,19 +824,65 @@ runs:
         find "$MODULES_SRC" -type f -name '*.ko' -print0 | xargs -0 zip -j "$MODULES_ZIP"
         echo "Packaged kernel modules to $MODULES_ZIP"
 
+    - name: Format build time
+      id: build_time
+      shell: bash
+      run: |
+        set -euo pipefail
+
+        if [ "$duration" -ge 60 ]; then
+          duration="$((duration / 60))m $((duration % 60))s"
+        else
+          duration="${duration}s"
+        fi
+
+        if [ "$duration_oplus_ext" -ge 60 ]; then
+          duration_oplus_ext="$((duration_oplus_ext / 60))m $((duration_oplus_ext % 60))s"
+        else
+          duration_oplus_ext="${duration_oplus_ext}s"
+        fi
+
+        if [ "$duration_qcom_ext" -ge 60 ]; then
+          duration_qcom_ext="$((duration_qcom_ext / 60))m $((duration_qcom_ext % 60))s"
+        else
+          duration_qcom_ext="${duration_qcom_ext}s"
+        fi
+
+        if [ "$duration_dtb_ext" -ge 60 ]; then
+          duration_dtb_ext="$((duration_dtb_ext / 60))m $((duration_dtb_ext % 60))s"
+        else
+          duration_dtb_ext="${duration_dtb_ext}s"
+        fi
+
+        echo "duration=$duration" >> "$GITHUB_OUTPUT"
+        echo "duration_oplus_ext=$duration_oplus_ext" >> "$GITHUB_OUTPUT"
+        echo "duration_qcom_ext=$duration_qcom_ext" >> "$GITHUB_OUTPUT"
+        echo "duration_dtb_ext=$duration_dtb_ext" >> "$GITHUB_OUTPUT"
+
     - name: Final Build Summary
       shell: bash
       run: |
         set -euo pipefail
         {
-          echo "CCache Statistics :"
-          echo "$(/usr/bin/ccache -s)"
-        } | tee summary.txt
-        {
           echo "### Kernel Modules Build Summary"
+          echo "----"
           echo ""
-          echo "CCache Statistics :"
-          echo "$(ccache -s -v)"
+          echo "> [!NOTE]"
+          echo "> Model: ${{ env.MODEL }}"
+          echo ""
+          echo "> [!IMPORTANT]"
+          echo "> - Vendor boot SHA256: ${{ steps.create_vendor_boot.outputs.vendor_boot_sha256 }}"
+          echo "> - Vendor dlkm SHA256: ${{ steps.create_vendor_dlkm.outputs.vendor_dlkm_sha256 }}"
+          echo ""
+          echo "> [!NOTE]"
+          echo "> - Modules build time: ${{ steps.build_time.outputs.duration }}"
+          echo "> - Oplus external modules build time: ${{ steps.build_time.outputs.duration_oplus_ext }}"
+          echo "> - Qcom external modules build time: ${{ steps.build_time.outputs.duration_qcom_ext }}"
+          echo "> - External dtbo build time: ${{ steps.build_time.outputs.duration_dtb_ext }}"
+          echo ""
+          echo "> [!IMPORTANT]"
+          echo "> ## CCache Statistics :"
+          echo "> $(ccache -s -v )"
         } >> "$GITHUB_STEP_SUMMARY"
 
     - name: Cleanup old ccache
